name: Run Playwright Tests
'on':
  push:
    branches: main
  pull_request:
    branches: main
Jobs:
  Playwright_regression_test-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 6.0.x
    - run: dotnet build
